# Generated by Django 3.0.7 on 2020-06-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scientists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='scientists',
            options={'verbose_name': 'Scientist', 'verbose_name_plural': 'Scientists'},
        ),
        migrations.AlterField(
            model_name='scientists',
            name='field',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scientists.Field'),
        ),
    ]
