# Generated by Django 3.0.7 on 2020-06-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scientists', '0003_auto_20200607_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientists',
            old_name='field_new',
            new_name='field',
        ),
    ]
